import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ApiCall2 from "./component/ApiCall2/ApiCall2";
import ApiCall from "./component/ApiCall/ApiCall";
import InputUpperCase from "./component/InputUpperCase.tsx/InputUpperCase";
import ApiCall3 from "./component/ApiCall3/ApiCall3";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div >
          <p>
            Prueba técnica consumo API
          </p>
        <div className={styles.center}>
          <ApiCall></ApiCall>
          <ApiCall2></ApiCall2>
          <ApiCall3></ApiCall3>
        </div>
        <div>
          <InputUpperCase></InputUpperCase>
        </div>
        </div>
        
      </main>
    </>
  );
}
