import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ApiCall from "./component/ApiCall";
import ApiCall2 from "./component/ApiCall2";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div>
          <p>
            Prueba técnica consumo API
          </p>
        <div className={styles.center}>
          <ApiCall></ApiCall>
          <ApiCall2></ApiCall2>
        </div>
        </div>
          

       
      </main>
    </>
  );
}
